USE [master]
GO

/****** Object:  Database [PruebaDBUBI]    Script Date: 21/01/2023 08:44:11 ******/
DROP DATABASE [PruebaDBUBI]
GO

/****** Object:  Database [PruebaDBUBI]    Script Date: 21/01/2023 08:44:11 ******/
CREATE DATABASE [PruebaDBUBI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaDBUBI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaDBUBI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaDBUBI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaDBUBI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaDBUBI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PruebaDBUBI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaDBUBI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PruebaDBUBI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PruebaDBUBI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaDBUBI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PruebaDBUBI] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaDBUBI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PruebaDBUBI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PruebaDBUBI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PruebaDBUBI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PruebaDBUBI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PruebaDBUBI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PruebaDBUBI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PruebaDBUBI] SET  READ_WRITE 
GO


